spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce_db
    username: ahmet
    password: ahmet
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    show-sql: true
  mail:
    host: localhost
    port: 1025
    username: ahmet
    password: ahmet
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000
  messages:
    basename: messages
  web:
    locale: en_US
    locale-resolver: fixed
logging:
  level:
    web: debug

# environment variables
encryption:
  salt:
    rounds: 10
jwt:
  issuer: eCommerce
  expiryInSeconds: 604800
  algorithm:
    key: SuperSecureKey

email:
  from: no-reply@ecommerce.com

app:
  frontend:
    url: http://ecommerce.com # dummy url
  backend:
    url: http://localhost:8080 # for dev environment