spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce_db
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    show-sql: true
  messages:
    basename: messages
  web:
    locale: en_US
    locale-resolver: fixed
logging:
  level:
    web: debug

# environment variables
encryption:
  salt:
    rounds: 10
jwt:
  issuer: eCommerce
  expiryInSeconds: 604800
  algorithm:
    key: SuperSecureKey